### PR TITLE
Don't cover Android virtual keyboard

### PR DESCRIPTION
**Pull request by RobbWatershed**
## Guidelines
Prevent PowerMenu from covering the Android virtual keyboard (#90)
Successfuly tested with the sample app

### Types of changes
What types of changes does your code introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Preparing a pull request for review
Ensure your change is properly formatted by running:

```gradle
$ ./gradlew spotlessApply
```

Please correct any failures before requesting a review.

### CODE REVIEW

**Comment by RobbWatershed** [comment]
FYI, screenshot of the fixed menu

image

**Comment by skydoves** [comment]
Hey @RobbWatershed,
Thank you for your contribution. Due to `INPUT_METHOD_NEEDED` was not imported to the file, the commit was broken. Could you fix this and push it? Thanks!

**Comment by RobbWatershed** [comment]
Sorry for that. I didn't commit from Android Studio but by hand, and completely forgot about imports.

It should be fine now.

**Review by skydoves — APPROVED** [review]
Looks good to me! Thank you for your contribution :)

**Pull request merged**
