### PR TITLE
Fix focus state

### PR DESCRIPTION
**Pull request by sebastienrouif**
### 🎯 Goal
When launching a menu, it currently does get focus which makes it impossible to access when using keyboard navigation

### 🛠 Implementation details
I simply set the window to be focusable

### ✍️ Explain examples
Example is no navigable through keyboard when using `.isFocusable`

### Preparing a pull request for review
Ensure your change is properly formatted by running:

```bash
$ ./gradlew spotlessApply
```

Then dump binary APIs of this library that is public in sense of Kotlin visibilities and ensures that the public binary API wasn't changed in a way that makes this change binary incompatible.

```bash
./gradlew apiDump
```

Please correct any failures before requesting a review.

## Code reviews
All submissions, including submissions by project members, require review. We use GitHub pull requests for this purpose. Consult [GitHub Help](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) for more information on using pull requests.

### CODE REVIEW

**Comment by sebastienrouif** [comment]
resolves https://github.com/skydoves/PowerMenu/issues/81

**Review by skydoves — APPROVED** [review]
Looks good to me :)

**Comment by sebastienrouif** [comment]
Thanks @skydoves , could you release a snapshot or full version ?

**Comment by sebastienrouif** [comment]
@skydoves I can't find the snapshot version on maven, is the snapshot release working? otherwise would you mind starting a release ?

**Comment by skydoves** [comment]
Hey @sebastienrouif, sorry for the late response. I will release the next stable version this week and let you know soon!
And thank you so much for your contribution :)

**Comment by sebastienrouif** [comment]
I was missing the second part

**Pull request merged**
